---

- name: 'download sum file'
  get_url:
    url: "{{ verify_artifact_sum_url }}"
    dest: "{{ verify_artifact_tmpdir }}/sum.asc"
    timeout: "{{ verify_artifact_download_timeout }}"

- name: 'download signature file'
  get_url:
    url: "{{ verify_artifact_signature_url }}"
    dest: "{{ verify_artifact_tmpdir }}/sig"
    timeout: "{{ verify_artifact_download_timeout }}"

- name: 'create gnupg directory'
  file:
    path: ~/.gnupg
    mode: '0700'
    state: 'directory'

- name: 'check signature file'
  shell: |
    gpg --no-tty --no-default-keyring --keyring {{ verify_artifact_tmpdir }}/keyring.gpg --trust-model always --import < {{ verify_artifact_tmpdir }}/pubkey.gpg && \
      gpg --no-tty --keyring {{ verify_artifact_tmpdir }}/keyring.gpg --verify {{ verify_artifact_tmpdir }}/sig {{ verify_artifact_tmpdir }}/sum.asc
  register: __verify_artifact_gpg_result
  failed_when: __verify_artifact_gpg_result.rc != 0
  changed_when: False

- name: 'download archive'
  get_url:
    url: "{{ verify_artifact_download_url }}"
    dest: "{{ verify_artifact_tmpdir }}/{{ verify_artifact_artifact_name }}"
    timeout: "{{ verify_artifact_download_timeout }}"

- name: 'checksum archive'
  shell: |
    {{ _verify_artifact_cksum_command }}
  args:
    chdir: "{{ verify_artifact_tmpdir }}"
  register: __verify_artifact_cksum_result
  failed_when: __verify_artifact_cksum_result.rc != 0
  changed_when: False
