---

- name: 'download sum file'
  get_url:
    url: "{{ verify_artifact_sum_url }}"
    dest: "{{ verify_artifact_tmpdir }}/sum.asc"
    timeout: "{{ verify_artifact_download_timeout }}"

- name: 'bogus sum file (like grafana)'
  replace:
    path: "{{ verify_artifact_tmpdir }}/sum.asc"
    regexp: "(.*)"
    replace: '\1 {{ verify_artifact_download_url | basename }}'
  when: >
    verify_artifact_sum_bogus is defined
    and verify_artifact_sum_bogus == 'missing-filename'

- name: 'download archive'
  get_url:
    url: "{{ verify_artifact_download_url }}"
    dest: "{{ verify_artifact_tmpdir }}/{{ verify_artifact_artifact_name }}"
    timeout: "{{ verify_artifact_download_timeout }}"

- name: 'checksum archive'
  shell: |
    {{ _verify_artifact_cksum_command }}
  args:
    chdir: "{{ verify_artifact_tmpdir }}"
  register: __verify_artifact_cksum_result
  failed_when: __verify_artifact_cksum_result.rc != 0
  changed_when: False
