---

driver:
  name: 'docker'

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .

platforms:
  - name: 'target-debian-${MOLECULE_INSTANCE_NAME_ID:-1}'
    image: '${MOLECULE_LINUX_DISTRIBUTION:-geerlingguy/docker-debian10-ansible:latest}'
    command: ''
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True

provisioner:
  name: 'ansible'
  config_options:
    defaults:
      stdout_callback: 'yaml'
      bin_ansible_callbacks: True
      interpreter_python: 'python3'
  options:
    D: True
  log: True

verifier:
  name: 'ansible'

scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
